REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_my_basket', 'Labels', 'EN', 'My basket');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_hello', 'Labels', 'EN', 'Hello');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_guest', 'Labels', 'EN', 'Guest');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_browse_main_sections', 'Labels', 'EN', 'browse main sections:');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_browse_main_sections_mobile', 'Labels', 'EN', 'browse main sections');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_buying_magazines', 'Labels', 'EN', 'Buying Magazines');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_selling_magazines', 'Labels', 'EN', 'Selling Magazines');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_advertising', 'Labels', 'EN', 'Advertising');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_who_we_are', 'Labels', 'EN', 'Who We Are');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_our_service', 'Labels', 'EN', 'Our Service');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_careers', 'Labels', 'EN', 'Careers');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_find_magazines_articles', 'Labels', 'EN', 'Find Magazines / Articles');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_bying_back_issues', 'Labels', 'EN', 'Buying Back Issues');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_bying_subscriptions', 'Labels', 'EN', 'Buying Subscriptions');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_delivery_rates_info', 'Labels', 'EN', 'Delivery Rates & Info');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_new_seller_overview', 'Labels', 'EN', 'New Seller Overview');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_seller_terms', 'Labels', 'EN', 'Seller Terms & Conditions');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_trade_services', 'Labels', 'EN', 'Trade Services');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_contribute_content', 'Labels', 'EN', 'Contribute Content');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_register_login', 'Labels', 'EN', 'Register / Log-In');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_advertising_overview', 'Labels', 'EN', 'Advertising Overview');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_rate_card', 'Labels', 'EN', 'Rate Card');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_make_booking', 'Labels', 'EN', 'Make Booking');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_now_delivering', 'Labels', 'EN', 'Now delivering to over 40 countries!');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_copyright_links', 'Labels', 'EN', 'Use constitutes acceptance of the <a href="index.php?target=help&section=conditions">Terms & Conditions</a>, <a href="">User Agreements</a> and <a href="index.php?target=help&section=business">Privacy Policy</a>.');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_classifieds', 'Labels', 'EN', 'CLASSIFIEDS');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_article_search', 'Labels', 'EN', 'article search');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_keywords', 'Labels', 'EN', 'Keywords');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_magazines_in_this_section', 'Labels', 'EN', 'magazines in this section:');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_magazine_titles', 'Labels', 'EN', 'magazine titles');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_subcategories_instruction', 'Labels', 'EN', '<span style="font-weight: bold; color: rgb(255, 0, 8);">Click logos</span> to view available content for that title.  Use <span style="font-weight: bold;">Previous</span> and <span style="font-weight: bold;">Next</span> to see more titles.');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_magazines', 'Labels', 'EN', 'Magazines');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_back_issues', 'Labels', 'EN', 'back issues');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_subscriptions', 'Labels', 'EN', 'subscriptions');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_current_issue', 'Labels', 'EN', 'current issue');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_about_this_title', 'Labels', 'EN', 'about this title');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_browse_issues', 'Labels', 'EN', '<span style="font-weight: bold; color: #ff0008;">Use buttons</span> to browse back issues of this title. Issues may be bought, sold and downloaded.');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_me_issues', 'Labels', 'EN', 'Issues');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_back_issues', 'Labels', 'EN', 'Back Issues');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_subscribtions_not_available', 'Labels', 'EN', 'Subscriptions not available for this title');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_no_longer_published', 'Labels', 'EN', 'This title is no longer published, or we are not aware of anyone selling subscriptions for it.');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_sorry_nothing_available', 'Labels', 'EN', 'Sorry - nothing available!');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_magazine_agents', 'Labels', 'EN', '<span style="font-weight: bold;">Magazine publishers &amp; subscription agents:- </span> <a href="/pages.php?pageid=23"><span style="font-weight: bold; color: rgb(3, 26, 252);">click here</span> </a>to be included on this page.');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_only_publisher', 'Labels', 'EN', '<span style="font-size: 11pt; font-weight: bold; color: rgb(255, 0, 0); text-align: center;">Only the publisher or distributor </span><span style="font-size: 11pt; color: rgb(0, 0, 0);"> of this title may contribute information to this page.</span>');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_view_full_listing', 'Labels', 'EN', 'View full listing page for this issue');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_full_me_page', 'Labels', 'EN', '(Full Magazine Exchange page - more information, buy and sell print editions, download digital editions)');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_free_me_page', 'Labels', 'EN', 'This is a free page created by Magazine Exchange using basic information supplied by the publisher. We welcome publishers to replace this page with one they control directly - that page can be of any design, with logos, images, weblinks, contact details and any other information they wish. <a href="/help-centre-selling-trade-services.html" class="ProductBlue">See Trade Services Guide.</a>');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_info_external', 'Labels', 'EN', 'Information on this page is provided by external sources and is not verified by Magazine Exchange.');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_this_magazine_title_published', 'Labels', 'EN', '<span style="font-size: 11pt; font-weight: bold; color: rgb(255, 0, 0); text-align: center;">If this magazine title</span><span style="font-size: 11pt; color: rgb(0, 0, 0);"> is still being published then only the publisher may contribute information to this page. Anyone may contribute information if the title is no longer being published.</span>');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_about_this_title', 'Labels', 'EN', 'About this title');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_info_not_provided', 'Labels', 'EN', 'Information not yet provided by publisher');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_still_in_publication', 'Labels', 'EN', 'This title is still in publication but the publisher hasn\'t yet supplied information for this page.<br>Publisher: <a href="#" class="ProductBlue">Send us your information now.</a> This is a free service!');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_publication_information', 'Labels', 'EN', 'Publication Information');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_publisher', 'Labels', 'EN', 'Publisher');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_country_lang', 'Labels', 'EN', 'Country / Language');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_frequency', 'Labels', 'EN', 'Frequency');
REPLACE INTO `cw_languages` (name, topic, code, value) VALUES ('lbl_current_issue', 'Labels', 'EN', 'Current Issue');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_view_all_products_in_category', '<< Return to Previous Page', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_print_edition', 'print edition', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_digital_edition', 'digital edition', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_buy_or_sell', 'Buy or sell copies of this magazine!', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_details_of_magazine', 'Details of this magazine', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'txt_details_of_magazine_text', '<p>Shown below are independent sellers with this item for sale. All sellers area UK-Based with identical shipping costs.</p><p>As a buyer, your order &amp; payment is securely processed by Magazine Exchange - the seller just receives your address details in order to dispatch the item directly to you.</p><p>You may purchase multiple items from different sellers in a single order - we\'ll sort it all out!</p>', 'Text');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_shipping_weight_kg', 'Shipping Weight kg', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_contents_listing', 'Contents Listing', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_see_below', 'See below', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_add_to_wl', 'Add to My Wanted List', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_sell_this_item', 'Sell this item', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_seller_descr', 'Seller\'s Description', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_seller_info', 'Seller Information', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_ready_to_buy', 'Ready to Buy?', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_currently_no_sellers', 'There are currently no sellers offering this item', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_digital_edition_feedback', 'Digital Editions Feedback', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_free_preview', 'Free Preview', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_buy_from_me', 'Buy from Magazine Exchange', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_buy_from_retailer', 'Buy from other Retailer', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'txt_digital_edition_text', '<p>Digital editions are printed magazines that have been converted to an electronic format for immediate download &amp; on-screen viewing.</p><p><b>Digital Editions from Magazine Exchange:-</b> <br>Purchase using normal Basket / Checkout system.</p><p><b>Digital Editions from other Retailers:-</b> <br>External website opens in new window.</p>', 'Text');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_learn_more', 'Learn more>', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_digital_edition', 'Digital Edition', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_articles_and_features', 'Contents Listing - Articles & Features in this issue', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_awaiting_entry', 'Awaiting Entry', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_article_snippets', 'Article Snippets', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_add_comments', 'Add Comments', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_improve_description', 'Improve Description', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_adverts_and_links', 'Adverts and Links based on this content', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_buy_a_subscription', 'Buy a subscription to this magazine', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_advertisement', 'Advertisement', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_advertise_your_business', 'Advertise your business', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_buy_sell_collections', 'Classifieds - buy and sell complete magazine collections', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_visit_classifieds_section', 'Visit Classifieds section', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_interested_in_this_page', 'Interested in this page?', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_log_into_cust_acc', 'Log-into your Customer (Buyer) account', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_forgotten_login_details', 'Forgotten login details?', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_problems_logging', 'Having problems logging in?', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_get_help', 'Get Help', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_dont_have_acc', 'Don\'t have an account yet?', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'txt_login_page', '<p>Access details of all your previous orders and other<br>special features only available to registered customers</p><p>Registration is quick and totally free.</p><p>(Note: This is for opening a Customer account - for<br>Seller accounts see the ''Sell'' tab on the top menu)</p>', 'Text');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'learn_more_about_benefits', 'Learn more about <a href="pages.php?pageid=10">Benefits of registering</a>', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'txt_error_http_404_upper_message', 'Whoops!', 'Text');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'txt_error_http_404_doesnt_exist', 'This page doesn\'t exist or is undergoing maintenance', 'Text');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'txt_error_http_404_lower_message', 'If you arrived at this page by clicking a link on the website please <a style="color: rgb(0, 0, 205);" href="mailto:info@magazineexchange.co.uk? » &subject=I broke your website!">let us know</a> so we can fix it.', 'Text');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_error_404', '404 Error', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_cart', 'Your shopping basket', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_update_qty_note', '(Note: only possible if Seller has multiple items)', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_submit_checkout', 'Submit &raquo;', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_cart_totals', 'Your Basket', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_cart_totals_note', 'Click the button on your right to show/hide your Basket contents.', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_forgotten_login_details', 'Forgotten login details?', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_billing_address', 'Billing Address', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_shipping_address', 'Shipping Address', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_register_benefits', '<b>Would you like to register?</b> It\'s free and gives access to lots of extra website features. Just tick the \'Register\' box below and choose your login details. Like to know more before deciding? Read about the Benefits of Registering', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_doc_info_O', 'Initial order details', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_doc_info_text', 'This section allows you to view order details.', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_invoice', 'Invoice', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_transaction', 'Transaction', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_items_purchased_me', 'Items purchased from Seller Magazine Exchange', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_call_us', 'CALL US', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_phone_2', '+44 (0)1773 781648', 'Labels');

REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_searching_browsing', 'Searching & Browsing', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_buying', 'Buying', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_subscribtions', 'Subscribtions', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_digital_editions', 'Digital Editions', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_legal_stuff', 'Legal Stuff', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_about_you', 'About You', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_managing_your_account', 'Managing Your Account', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_info_rates', 'Information & Rates', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_help_guides', 'HELP GUIDES', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_help_centre_home', 'HELP CENTRE HOME', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'txt_help_zone_title', 'Click a Help Guide below or a Quick Link from the left menu:', 'Text');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_quick_start_quides', 'QUICK START GUIDES', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_quide_new_seller', 'Guide for New Sellers', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_searching_for_articles', 'Searching for Articles', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_delivery_rates_info', 'Delivery Rates & Info.', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_adding_data_to_site', 'Adding Data to Website', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_other_quick_links', 'OTHER QUICK LINKS', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_payment_options', 'Payment Options', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_browse_all_adverts', 'Browse All Adverts', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_search_adverts', 'Search Adverts', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_place_new_advert', 'Place New Advert', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_classifieds_help', 'Classifieds Help', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_what_section_is_for', 'What this section is for...', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_buying_items_with_classifieds', 'Buying items with Classifieds', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_selling_items_with_classifieds', 'Selling items with Classifieds', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_heavy_item', 'Heavy item delivery advice!', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_placing_a_wanted_advert', 'Placing a WANTED Advert', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_featured_classifieds', 'Featured Classifieds', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_no_ads_to_show', 'There are currently no Ads to show.', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_search_ads_by_keyword', 'Search adverts by keyword', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_see_adverts_collections', '<span style="font-size: 11pt; font-weight: bold; color: rgb(255, 0, 0); text-align: center;">Click links </span><span style="font-size: 11pt; color: #000;">below to see adverts offering collections of magazines covering that topic.</span>', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_help_zone', 'Help Centre Home', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_view_titles', 'View Titles', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_listed_by_marque', 'LISTED BY MARQUE', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_all_magazines', 'ALL MAGAZINES', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_find_articles', 'FIND ARTICLES', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_aatc_comment', '*Click <a href="index.php?target=cart">My Basket</a> link on main page to see<br> more details and edit basket contents', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_orders_step_1', 'Orders Received - Step 1 - Search for Orders <p>Select which orders you'd like to view:- </p>', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_orders_explanation', '<p><u>Explanation of Order Statuses:-</u></p><strong>Queued</strong><p>Your card payment has been authorised and confirmed; at the stage the payment is referred to as \'queued\' because we are still waiting for it to arrive, but we know it\'s on the way so we\'ll process your order without delay.</p><strong>Payment Received </strong><p>Your payment has been received - thankyou!</p><strong>Not Finished </strong><p>This might mean that a problem has occurred, but often simply means that there has been a delay in the communication telling us that your card payment or Paypal payment has been processed. If you are aware that the payment wasn\'t completed properly then don\'t worry - we can easily send you a new Paypal invoice by email, or you can telephone us with your card details. Once the payment has been received we will process your order as normal.</p><strong>Despatched </strong><p>Your order has been processed and despatched by the requested delivery service.</p>', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_number_of_pages', 'Number of Pages', 'Labels');

REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_click_cover_images', '<span style="font-weight: bold; color: rgb(255, 0, 8);">Click cover images</span> to view details of that issue.  Use <span style="font-weight: bold;">Previous</span> and <span style="font-weight: bold;">Next</span> to see more issues.', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_fiends_email', 'Recipient's e-mail', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_existing_seller_login', 'Existing Seller - Login', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_new_seller_registration', 'New Seller - Registration', 'Labels');

REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_reg_customer_acc', 'Registration - Customer Accounts', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_reg_customer_acc_text', 'Use this form to open a Customer <b>(Buying)</b> account...to open a <b>Selling</b> account choose that option from the \'My Mags\' menu above.', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_reg_customer_acc_note', 'Just so you know...you can buy magazines <u>without</u> opening an account, but having an account makes things easier and gives access to extra website features. Don't worry - it's completely free and we're not going to bombard you with spam!');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_reg_terms', '(Clicking "Submit" button is to accept our <a href="index.php?target=help&section=conditions" target="_blank"><b>Terms &amp; Conditions</b>).</a>');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_reg_more_info', '<b>Notes:<br></b><br><li><font color="#053EE2">Usernames</font> - Usernames may contain numbers (0-9) and lower-case letters (a-z) only, and be no more than 32 characters long.</li><br><li><font color="#053EE2">Passwords</font> - Passwords are case sensitive (must always be typed exactly the same way).</li><br><li><font color="#053EE2">Email</font>- E-mail addresses must be valid! Please double-check the address before clicking \'Submit\'.</li><br><li>All your private data is held confidentially and will not be sold or distributed in any way for marketing purposes. If you buy items from third-party sellers on this site your delivery details will be released to them so your goods can be despatched.</li><br><br>For further information refer to our:- <a target="_blank" href="index.php?target=help&section=conditions"><font style="white-space: nowrap;" class="Text"><b> Terms &amp; Conditions</b> </font></a>');

