INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_breadcrumbs_management', 'Breadcrumbs management', 'Labels');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_unknown_links', 'Unknown links', 'Labels');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_parent_link', 'Parent link', 'Labels');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_add_new_breadcrumb', 'Add new breadcrumb', 'Labels');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_breadcrumbs', 'Breadcrumbs', 'Labels');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'addon_name_breadcrumbs', 'Breadcrumbs', 'Addons');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'msg_err_link_already_exists', 'The specified link already exists.', 'Labels');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'msg_breadcrumb_updated', 'Breadcrumb has been successfully updated', 'Labels');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'msg_breadcrumb_added', 'New breadcrumb has been successfully added', 'Labels');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_select_breadcrumb', 'Select breadcrumb', 'Labels');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'txt_use_any_as_sequence_of_digits', 'Use "[[ANY]]" to set the sequence of digits', 'Text');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'txt_you_can_not_delete_active_link', 'You can not delete an active link', 'Text');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'txt_selected_breadcrumbs_deleted', 'The selected breadcrumbs have been deleted', 'Text');
INSERT INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_uniting', 'Uniting', 'Labels');

DROP TABLE IF EXISTS `cw_breadcrumbs`;
CREATE TABLE IF NOT EXISTS `cw_breadcrumbs` (
  `breadcrumb_id` int(11) NOT NULL AUTO_INCREMENT,
  `link` varchar(255) NOT NULL,
  `title` varchar(2048) NOT NULL,
  `parent_id` int(11) NOT NULL DEFAULT '0',
  `addon` varchar(255) NOT NULL DEFAULT '',
  `uniting` smallint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`breadcrumb_id`),
  KEY `link` (`link`)
) ENGINE=MyISAM  DEFAULT CHARSET=cp1251 AUTO_INCREMENT=214 ;

INSERT INTO `cw_breadcrumbs` (`breadcrumb_id`, `link`, `title`, `parent_id`, `addon`, `uniting`) VALUES
(1, '/index.php', 'lbl_area_admin', 0, '', 0),
(2, '/index.php?target=docs_O', 'lbl_orders', 1, '', 0),
(3, '/index.php?target=user_C', 'lbl_customers', 1, '', 0),
(4, '/index.php?target=user_C&mode=add', 'lbl_user_create_C', 3, '', 0),
(5, '/index.php?target=shipping', 'lbl_shipping_methods', 1, 'shipping_system', 0),
(6, '/index.php?target=giftcerts', 'lbl_gift_certificates', 1, 'estore_gift', 0),
(7, '/index.php?target=docs_I', 'lbl_invoice', 1, '', 0),
(8, '/index.php?target=pages', 'lbl_static_pages', 1, '', 0),
(9, '/index.php?target=mail_queue', 'lbl_mail_queue', 1, '', 1),
(10, '/index.php?target=settings', 'lbl_settings', 1, '', 0),
(11, '/index.php?target=user_C&mode=search', 'Customers search', 3, '', 0),
(12, '/index.php?target=user_C&mode=modify&user=[[ANY]]', 'lbl_modify_customer', 11, '', 0),
(23, '/index.php?target=promosuite', 'lbl_offers', 1, 'promotion_suite', 0),
(21, '/index.php?target=select_breadcrumb', 'lbl_select_breadcrumb', 1, '', 1),
(20, '/index.php?target=breadcrumbs_management', 'lbl_breadcrumbs_management', 1, 'breadcrumbs', 1),
(32, '/index.php?target=domains&action=copy_basic&domain_id=[[ANY]]', 'lbl_mdm_copy_basic_skin', 31, 'multi_domains', 0),
(31, '/index.php?target=domains', 'lbl_domains', 1, 'multi_domains', 0),
(38, '/index.php?target=categories&mode=edit&cat=[[ANY]]', 'lbl_modify_category', 37, '', 0),
(30, '/index.php?target=domains&mode=config&domain_id=[[ANY]]', 'lbl_edit_config', 31, 'multi_domains', 0),
(28, '/index.php?target=promosuite&action=form&offer_id=', 'lbl_ps_new_offer', 1, 'promotion_suite', 0),
(34, '/index.php?target=domains&action=cleanup&domain_id=[[ANY]]', 'lbl_mdm_compare_cleanup', 31, 'multi_domains', 0),
(37, '/index.php?target=categories', 'lbl_categories', 1, '', 0),
(39, '/index.php?target=clean_url_show_history', 'History clean urls', 1, '', 1),
(40, '/index.php?target=categories&cat=[[ANY]]', 'lbl_subcategories', 37, '', 0),
(41, '/index.php?target=categories&mode=products&cat=[[ANY]]', 'lbl_category_products', 37, '', 0),
(42, '/index.php?target=configuration', 'lbl_addons', 10, '', 0),
(47, '/index.php?target=meta_tags', 'lbl_seo_setting', 10, '', 0),
(44, '/index.php?target=license', 'lbl_license', 10, '', 0),
(45, '/index.php?target=addons_manager', 'lbl_install_addon', 42, '', 0),
(46, '/index.php?target=configuration&mode=addons', 'lbl_addons', 10, '', 1),
(48, '/index.php?target=clean_urls_list', 'lbl_clean_urls_list', 47, '', 0),
(49, '/index.php?target=payments&mode=methods', 'lbl_payment_methods', 10, 'payment_system', 0),
(50, '/index.php?target=payments&mode=methods&payment_id=', 'lbl_payment_method_add', 49, 'payment_system', 0),
(51, '/index.php?target=payments&mode=methods&payment_id=[[ANY]]', 'lbl_modify_payment_method', 49, 'payment_system', 0),
(53, '/index.php?target=import&mode=impdata', 'lbl_import_data', 1, '', 0),
(54, '/index.php?target=import&mode=xcart', 'lbl_import_xcart', 1, '', 0),
(55, '/index.php?target=import&mode=expdata', 'lbl_export_data', 1, '', 0),
(56, '/index.php?target=google_base', 'lbl_google_export', 1, 'google_base', 0),
(57, '/index.php?target=ebay_export', 'lbl_ebay_export', 1, 'ebay', 0),
(58, '/index.php?target=logs', 'lbl_shop_logs', 1, '', 0),
(59, '/index.php?target=db_backup', 'lbl_database_backup_restore', 1, '', 0),
(60, '/index.php?target=sitemap_xml', 'lbl_sitemap_xml', 1, 'sitemap_xml', 0),
(61, '/index.php?target=sessions', 'lbl_sessions', 1, '', 1),
(63, '/index.php?target=message_box', 'lbl_messages', 1, 'messaging_system', 0),
(64, '/index.php?target=message_box&mode=new', 'lbl_new_message', 63, 'messaging_system', 0),
(65, '/index.php?target=message_box&mode=sent', 'lbl_sent', 63, 'messaging_system', 0),
(66, '/index.php?target=message_box&mode=archive', 'lbl_archive', 63, 'messaging_system', 0),
(67, '/index.php?target=taxes', 'lbl_taxes', 5, '', 0),
(68, '/index.php?target=zones', 'lbl_taxing_zones', 67, '', 0),
(69, '/index.php?target=countries', 'lbl_countries', 5, '', 1),
(85, '/index.php?target=shipping&shipping_id=[[ANY]]', 'lbl_shipping_modify', 5, 'shipping_system', 0),
(92, '/index.php?target=dashboard', 'lbl_dashboard', 10, 'dashboard', 0),
(91, '/index.php?target=cod_types', 'lbl_cod_types', 5, '', 0),
(90, '/index.php?target=shipping_rates', 'lbl_shipping_rates', 5, 'shipping_system', 0),
(89, '/index.php?target=shipping_zones&mode=add', 'Add Shipping Zone', 86, 'shipping_system', 0),
(76, '/index.php?target=taxes&mode=add', 'Add tax', 67, '', 0),
(77, '/index.php?target=taxes&tax_id=[[ANY]]', 'lbl_tax_details', 67, '', 0),
(78, '/index.php?target=zones&zone_id=[[ANY]]', 'lbl_zone_details', 68, '', 0),
(79, '/index.php?target=zones&mode=add', 'Add taxing zone', 68, '', 0),
(84, '/index.php?target=shipping&shipping_id=', 'lbl_shipping_add', 5, 'shipping_system', 0),
(88, '/index.php?target=shipping_zones&zone_id=[[ANY]]', 'Modify Shipping Zone', 86, 'shipping_system', 0),
(87, '/index.php?target=shipping_carriers', 'lbl_carriers', 5, 'shipping_system', 0),
(86, '/index.php?target=shipping_zones', 'lbl_shipping_zones', 5, 'shipping_system', 0),
(93, '/index.php?target=pages&page_id=', 'lbl_add_static_page', 8, '', 0),
(94, '/index.php?target=pages&page_id=[[ANY]]', 'lbl_modify_static_page', 8, '', 0),
(95, '/index.php?target=news', 'lbl_news_management', 1, 'news', 0),
(96, '/index.php?target=news&list_id=', 'lbl_create_news', 95, 'news', 0),
(97, '/index.php?target=news&list_id=[[ANY]]', 'lbl_modify_news', 95, 'news', 0),
(98, '/index.php?target=news&js_tab=subscriptions', 'lbl_news_management', 95, 'news', 1),
(100, '/index.php?target=news_c', 'lbl_customer_side_news', 1, 'news', 0),
(101, '/index.php?target=news_c&list_id=', 'lbl_create_customer_side_news', 100, 'news', 0),
(102, '/index.php?target=news_c&list_id=[[ANY]]', 'lbl_modify_customer_side_news', 100, 'news', 0),
(103, '/index.php?target=news_c&messageid=[[ANY]]&list_id=[[ANY]]&js_tab=message', 'lbl_news_management', 100, 'news', 0),
(104, '/index.php?target=news_c&js_tab=subscriptions', 'lbl_news_management', 100, 'news', 1),
(105, '/index.php?target=news_c&list_id=[[ANY]]&js_tab=add_message', 'lbl_news_management', 100, 'news', 0),
(106, '/index.php?target=ad_banners&mode=list', 'lbl_ab_ad_banners', 1, 'ad_banners', 1),
(107, '/index.php?target=ad_banners&mode=search', 'lbl_search', 106, 'ad_banners', 0),
(108, '/index.php?target=ad_banner&mode=add', 'lbl_ab_add_new_banner', 106, '', 0),
(112, '/index.php?target=languages', 'lbl_languages', 1, '', 1),
(116, '/index.php?target=speed_bar&speed_id=', 'Add Speed Bar', 115, '', 0),
(111, '/index.php?target=ad_banner&mode=update&banner_id=[[ANY]]', 'lbl_ab_update_banner', 106, '', 0),
(115, '/index.php?target=speed_bar', 'lbl_speed_bar', 1, '', 0),
(117, '/index.php?target=speed_bar&speed_id=[[ANY]]', 'Modify Speed Bar', 115, '', 0),
(118, '/index.php?target=special_images', 'lbl_special_images', 115, '', 0),
(119, '/index.php?target=image_selection', 'lbl_image_selection', 1, '', 1),
(120, '/index.php?target=custom_css', 'lbl_css_styles', 115, '', 0),
(121, '/index.php?target=sections_pos', 'lbl_sections_position', 1, '', 0),
(122, '/index.php?target=estore_stop_list', 'lbl_stop_list', 1, 'estore_products_review', 0),
(123, '/index.php?target=estore_reviews_management', 'lbl_reviews_management', 1, 'estore_products_review', 1),
(134, '/index.php?target=user_A', 'lbl_admins', 1, '', 0),
(128, '/index.php?target=giftcerts&mode=add_gc', 'Add Gift Certificate', 6, 'estore_gift', 0),
(129, '/index.php?target=giftcerts&action=print', 'Print Giftcertificate', 6, 'estore_gift', 1),
(127, '/index.php?target=user_C&mode=purchased_products&user=[[ANY]]', 'lbl_register_field_sections_purchased_products', 1, '', 0),
(130, '/index.php?target=giftcerts&mode=modify_gc', 'lbl_view_gift_certificate', 6, 'estore_gift', 1),
(138, '/index.php?target=user_A&mode=add', 'lbl_user_create_A', 134, '', 0),
(137, '/index.php?target=user_A&mode=purchased_products&user=[[ANY]]', 'lbl_register_field_sections_purchased_products', 134, '', 0),
(135, '/index.php?target=user_A&mode=search', 'Search Admin', 134, '', 0),
(136, '/index.php?target=user_A&mode=modify&user=[[ANY]]', 'lbl_user_modify_A', 134, '', 0),
(139, '/index.php?target=memberships', 'lbl_memberships', 1, '', 0),
(140, '/index.php?target=access_level&mem_area=A&membership_id=[[ANY]]', 'lbl_access_level', 139, '', 0),
(141, '/index.php?target=user_profiles', 'lbl_profile_options', 1, '', 0),
(142, '/index.php?target=user_profiles&user_type=A', 'lbl_admins', 141, '', 0),
(143, '/index.php?target=user_profiles&mode=fields', 'lbl_additional_sections', 141, '', 0),
(144, '/index.php?target=docs_O&mode=search', 'lbl_search_orders', 2, '', 1),
(146, '/index.php?target=docs_O&mode=details&doc_id=[[ANY]]', 'lbl_doc_info_O', 144, '', 0),
(147, '/index.php?target=docs_O&doc_id=[[ANY]]', 'lbl_doc_info_O', 144, '', 0),
(148, '/index.php?target=docs_O&doc_id=[[ANY]]&mode=print', 'lbl_doc_info_O', 144, '', 0),
(149, '/index.php?target=docs_O&doc_id=[[ANY]]&mode=edit', 'lbl_order_info', 144, '', 1),
(150, '/index.php?target=popup_users', 'lbl_popup_users', 1, '', 1),
(157, '/index.php?target=docs_I&mode=details&doc_id=[[ANY]]', 'lbl_doc_info_I', 155, '', 0),
(155, '/index.php?target=docs_I&mode=search', 'Search quotes', 7, '', 1),
(154, '/index.php?target=docs_O&action=add', 'lbl_create_order', 2, '', 0),
(158, '/index.php?target=docs_I&doc_id=[[ANY]]', 'lbl_doc_info_I', 155, '', 0),
(159, '/index.php?target=docs_I&doc_id=[[ANY]]&mode=print', 'lbl_doc_info_I', 155, '', 0),
(160, '/index.php?target=docs_I&doc_id=[[ANY]]&mode=edit', 'Invoice Info', 155, '', 1),
(161, '/index.php?target=popup_products', 'Popup products', 1, '', 1),
(180, '/index.php?target=products&mode=clone&product_id=[[ANY]]', 'Product clone', 166, '', 0),
(168, '/index.php?target=manufacturers', 'lbl_manufacturers', 1, 'manufacturers', 1),
(163, '/index.php?target=docs_I&action=add', 'lbl_doc_create_I', 7, '', 0),
(167, '/index.php?target=categories&mode=add&cat=', 'lbl_add_category', 37, '', 0),
(166, '/index.php?target=products', 'lbl_products', 1, '', 0),
(190, '/index.php?target=attributes&attribute_class_id=', 'Add Feature Class', 189, '', 0),
(178, '/index.php?target=products&mode=add', 'lbl_add_product', 166, '', 0),
(172, '/index.php?target=manufacturers&mode=add', 'lbl_add_manufacturer', 168, 'manufacturers', 0),
(176, '/index.php?target=warranties', 'lbl_warranties', 1, '', 0),
(177, '/index.php?target=warranties&warranty_id=[[ANY]]', 'Modify warranty', 176, '', 0),
(174, '/index.php?target=products&mode=search', 'Product search', 166, '', 1),
(175, '/index.php?target=manufacturers&manufacturer_id=[[ANY]]', 'Modify manufacturer', 168, 'manufacturers', 0),
(181, '/index.php?target=products&mode=details', 'lbl_product_modify', 174, '', 1),
(189, '/index.php?target=attributes', 'lbl_attributes_classes', 1, '', 0),
(183, '/index.php?target=products_clients&product_id=[[ANY]]', 'Products clients', 1, '', 0),
(187, '/index.php?target=special_sections', 'lbl_special_sections', 1, '', 0),
(188, '/index.php?target=coupons', 'lbl_coupons', 1, 'discount_coupons', 0),
(185, '/index.php?target=popup_files', 'Popup files', 1, '', 0),
(193, '/index.php?target=attributes&mode=att', 'lbl_features', 1, '', 1),
(192, '/index.php?target=attributes&attribute_class_id=[[ANY]]', 'Modify Feature Class', 189, '', 0),
(194, '/index.php?target=attributes&mode=att&attribute_id=', 'Add Feature', 193, '', 0),
(195, '/index.php?target=attributes&mode=att&attribute_id=[[ANY]]', 'Modify Feature', 193, '', 0),
(196, '/index.php?target=register&mode=modify', 'lbl_customers', 1, '', 0),
(197, '/index.php?target=surveys', 'lbl_survey', 1, 'survey', 0),
(198, '/index.php?target=surveys&survey_id=[[ANY]]', 'lbl_modify_survey', 197, 'survey', 1),
(202, '/index.php?target=tabs', 'Tabs', 1, '', 0),
(204, '/index.php?target=tabs&section_id=[[ANY]]', 'Modify Tab', 202, '', 0),
(205, '/index.php?target=amazon_export', 'lbl_amazon_export', 1, 'amazon', 0),
(206, '/index.php?target=offers', 'lbl_special_offers', 1, 'special_offers', 0),
(207, '/index.php?target=offers&action=create', 'Add Special Offer', 206, 'special_offers', 0),
(208, '/index.php?target=offers&mode=conditions&offer_id=[[ANY]]', 'Modify Special Offer', 206, 'special_offers', 0),
(209, '/index.php?target=offers&offer_id=[[ANY]]', 'Modify Special Offer', 206, 'special_offers', 1),
(210, '/index.php?target=offers&mode=modify&offer_id=[[ANY]]', 'Modify Special Offer', 206, 'special_offers', 0),
(213, '/index.php?target=estore_review_management&review_id=[[ANY]]&product_id=[[ANY]]', 'lbl_reviews_management', 1, 'estore_products_review', 0);

-- get menu_id for navigation menu
SELECT @sections:=menu_id FROM cw_navigation_menu WHERE title='lbl_content' AND parent_menu_id=0 AND area='A' LIMIT 1;
-- insert new entry to menu
DELETE FROM cw_navigation_menu WHERE title='lbl_breadcrumbs';
INSERT INTO `cw_navigation_menu` (`menu_id`, `parent_menu_id`, `title`, `link`, `orderby`, `area`, `access_level`, `addon`, `is_loggedin`) 
VALUES (NULL, @sections, 'lbl_breadcrumbs', 'index.php?target=breadcrumbs_management', 500, 'A', '', 'breadcrumbs', 1);

DELETE FROM cw_addons WHERE addon='breadcrumbs';
INSERT INTO `cw_addons` (`addon`, `descr`, `active`, `status`, `parent`,`version`,`orderby`)
VALUES ('breadcrumbs', 'Breadcrumbs', 1, 1, '', '0.1',0);
