delete from cw_languages where name like 'addon_name_%';

INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_accessories','Accessories','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_ad_banners','Ad Banners','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_ajax_add2cart','Ajax Add To Cart','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_amazon','Amazon','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_barcode','Barcode','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_bestsellers','Bestsellers','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_bookmarks','Bookmarks','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_clean_urls','Clean Urls','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_dashboard','Dashboard','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_demo_module','Demo Module','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_detailed_product_images','Detailed Product Images','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_discount_coupons','Discount Coupons','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_ebay','Ebay','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_egoods','Egoods','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_estore_category_tree','EStore Category Tree','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_estore_gift','EStore Gift','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_estore_products_review','EStore Products Review','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_faq','FAQ','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_fbauth','FB Auth','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_feedback_report','Feedback Report','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_froogle','Froogle','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_google_analytics','Google Analytics','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_google_base','Google Base','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_google_checkout','Google Checkout','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_image_verification','Image Verification','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_interneka','Interneka','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_magnifier','Magnifier','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_mailchimp_subscription','Mailchimp Subscription','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_manufacturers','Manufacturers','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_mobile','Mobile','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_multi_domains','Multi Domains','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_news','News','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_now_online','Now Online','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_order_tracking','Order Tracking','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_payment_authorize_sim','Payment. Authorize SIM','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_payment_system','Payment System','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_paypal_express',' PayPal Express','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_pos','POS','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_ppd','Product Page Download','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_product_options','Product Options','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_product_tabs','Product Tabs','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_remember_anonymouse_carts','Remember Anonymouse Carts','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_shipping_fedex','Shipping. FedEx','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_shipping_label_generator','Shipping Label Generator','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_shipping_system','Shipping System','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_shipping_tnt','Shipping. TNT','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_shipping_ups','Shipping. UPS','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_sitemap_xml','Sitemap XML','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_sn','Serial Numbers','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_special_offers','Special Offers','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_survey','Survey','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_top_menu','Top Menu','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_wholesale_trading','Wholesale Trading','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_promotion_suite','Promotion Suite','Addons');

INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_payment_cc','Payment. Credit Card','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_payment_ch','Payment. Check','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_payment_dd','Payment. DD','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_payment_gift_certificate','Payment. Gift Certificate','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_payment_offline','Payment. Offline','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_payment_sagepay_form','Payment. SagePay Form','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_payment_sagepay_server','Payment. SagePay Server','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_paypal','PayPal','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_paypal_pro','PayPal Pro','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_paypal_pro_payflow','PayPal Pro Payflow','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_quote_system','Quote System','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_redirect_after_login','Redirect After Login','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_seo_map','SEO Map','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_shipping_australia_post','Shipping. Australia Post','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_shipping_canada_post','Shipping. Canada Post','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_shipping_dhl','Shipping. DHL','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_shipping_intershipper','Shipping. Intershipper','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_shipping_usps','Shipping. USPS','Addons');
INSERT INTO cw_languages (code,name,value,topic) VALUES ('en','addon_name_special_products','Special Products','Addons');

