delete from cw_navigation_menu where title='lbl_edit_templates';
delete from cw_languages where name in (
'lbl_edit_templates',
'txt_delete_file_warning',
'lbl_create_new_file',
'lbl_create_new_directory',
'lbl_new_directory_name',
'lbl_copy_file_name',
'lbl_upload_file_to_directory',
'lbl_rewrite_file_if_exists',
'lbl_restore_all',
'lbl_compile_templates',
'lbl_browse_files',
'txt_restore_templates_warning',
'txt_compile_templates_warning',
'lbl_edit_file',
'lbl_preview_default_css',
'txt_edit_file_top_text',
'txt_preview_template_note',
'txt_delete_file_warning',
'txt_restore_templates_warning',
'txt_restore_templates_text',
'txt_compile_templates',
'txt_compile_templates_note',
'txt_directory_is_not_writable');
