REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_specials', 'Specials', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_follow_us', 'Follow us', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_facebook', 'Facebook', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_twitter', 'Twitter', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_add_to_wl', '<i class="icon_wl"></i>Add to wish list', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'txt_displaying_X_Y_results', 'Showing {{first_item}} - {{last_item}} of {{items}} results ', 'Text');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_share', 'Share', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_tweet', 'Tweet', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_google', 'Google', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_pinterest', 'Pinterest', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_read_reviews', 'Read reviews', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_only_registered', '<a href="index.php?target=help&section=login_customer" class="need_login">Log in</a> or <a href="index.php?target=acc_manager&usertype=C">register</a> to write review', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_unit_price', 'Unit Price', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_create_an_account', 'Create an account', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_already_registered', 'Already registered?', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_forgot_your_password', 'Forgot your password?', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_there_are_x_items_in_cart', 'There are {{items}} items in your cart', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_successfully_added', 'Product successfully added to your shopping cart', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_proceed_to_checkout', 'Proceed to checkout <i class="icon-chevron-right"></i>', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_continue_shopping', '<i class="icon-chevron-left"></i> Continue shopping', 'Labels');
REPLACE INTO `cw_languages` (`code`, `name`, `value`, `topic`) VALUES ('EN', 'lbl_compact_view_icon', '<i class="fa-navicon"></i> Compact', 'Labels');
