--
-- Table structure for table `cw_menu`
--

DROP TABLE IF EXISTS `cw_menu`;
CREATE TABLE `cw_menu` (
  `menu_id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_menu_id` int(11) NOT NULL DEFAULT '0',
  `title` varchar(255) NOT NULL DEFAULT '',
  `link` varchar(255) NOT NULL DEFAULT '',
  `target` varchar(64) NOT NULL,
  `orderby` int(11) NOT NULL DEFAULT '0',
  `area` char(1) NOT NULL DEFAULT '',
  `access_level` varchar(16) NOT NULL DEFAULT '',
  `func_visible` varchar(128) NOT NULL,
  `addon` varchar(255) NOT NULL DEFAULT '',
  `skins_subdir` varchar(64) NOT NULL,
  `is_loggedin` int(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`menu_id`),
  KEY `target` (`target`)
) ENGINE=MyISAM;

--
-- Dumping data for table `cw_menu`
--

LOCK TABLES `cw_menu` WRITE;
INSERT INTO `cw_menu` VALUES (36,3,'lbl_domains','index.php?target=domains','domains',1760,'A','','','multi_domains','',1),
(34,7,'lbl_sessions','index.php?target=sessions','sessions',1720,'A','','','','',1),
(33,7,'lbl_sitemap','index.php?target=sitemap_xml','sitemap_xml',1700,'A','','','sitemap_xml','sitemap_xml',1),
(31,7,'lbl_db_backup_restore','index.php?target=db_backup','db_backup',1680,'A','','','','',1),
(30,7,'lbl_shop_logs','index.php?target=logs','logs',1620,'A','','','','',1),
(29,7,'lbl_export_data','index.php?target=import&mode=expdata','import',1600,'A','1300','','','import_export',1),
(152,151,'lbl_products','index.php?target=products','products',360,'V','','','seller','products',1),
(28,7,'lbl_import_data','index.php?target=import&mode=impdata','import',1580,'A','1300','','','import_export',1),
(27,6,'lbl_taxes','index.php?target=taxes','taxes',1560,'A','','','','taxes',1),
(26,6,'lbl_shipping_methods','index.php?target=shipping','shipping',1540,'A','','','shipping_system','shipping-system',1),
(25,5,'lbl_speed_bar','index.php?target=speed_bar','speed_bar',1520,'A','','','','webmaster',1),
(24,5,'lbl_languages','index.php?target=languages','languages',1500,'A','','','','languages',1),
(22,5,'lbl_cs_content_sections','index.php?target=cms&mode=list','cms',1480,'A','','','cms','cms',1),
(20,5,'lbl_news_management','index.php?target=news','news',1420,'A','','','news','news',1),
(19,5,'lbl_static_pages','index.php?target=cms&mode=list&cs_type=staticpage','cms',1400,'A','','','cms','cms',1),
(18,4,'lbl_memberships','index.php?target=memberships','memberships',1380,'A','','','','memberships',1),
(17,4,'lbl_users_A','index.php?target=user_A','user_A',1320,'A','','','','users',1),
(16,4,'lbl_users_C','index.php?target=user_C','user_C',1300,'A','','','','users',1),
(15,3,'lbl_products','index.php?target=products','products',1260,'A','','','','products',1),
(14,3,'lbl_categories','index.php?target=categories','categories',1240,'A','','','','products',1),
(13,2,'lbl_invoices','index.php?target=docs_I','docs_I',1220,'A','','','','orders',1),
(12,2,'lbl_gift_certificates','index.php?target=giftcerts','giftcerts',1200,'A','0802','','estore_gift','',1),
(10,2,'lbl_orders','index.php?target=docs_O','docs_O',1040,'A','','','','orders',1),
(151,0,'lbl_catalog','index.php?target=products','products',20,'V','','','seller','products',1),
(8,0,'lbl_settings','index.php?target=settings','settings',170,'A','','','','settings',1),
(7,0,'lbl_tools','','',160,'A','','','','users',1),
(5,0,'lbl_content','','',120,'A','','','','users',1),
(6,0,'lbl_shipping_and_taxes','index.php?target=shipping','shipping',140,'A','','','','shipping-system',1),
(4,0,'lbl_users','index.php?target=user_C','user_C',90,'A','','','','users',1),
(3,0,'lbl_catalog','index.php?target=products','products',80,'A','','','','products',1),
(2,0,'lbl_orders','index.php?target=docs_O','docs_O',60,'A','','','','orders',1),
(149,7,'lbl_messages','index.php?target=message_box','message_box',1740,'A','','','messaging_system','',1),
(40,8,'lbl_general_settings','index.php?target=settings','settings',1800,'A','','','','settings',1),
(41,8,'lbl_addons','index.php?target=configuration','configuration',1860,'A','','','','configuration',1),
(42,8,'lbl_payment_methods','index.php?target=payments&mode=methods','payments',1880,'A','','','payment_system','',1),
(156,2,'lbl_discount_coupons','index.php?target=coupons','coupons',1280,'A','1209','','discount_coupons','',1),
(44,8,'lbl_search_engine_settings','index.php?target=meta_tags','meta_tags',1900,'A','','','','seo',1),
(45,4,'lbl_profile_options','index.php?target=user_profiles','user_profiles',1920,'A','','','','profile_options',1),
(46,6,'lbl_countries_and_states','index.php?target=countries','countries',1960,'A','','','','map',1),
(47,5,'lbl_sections_position','index.php?target=sections_pos','sections_pos',2000,'A','','','','',1),
(146,8,'lbl_license','index.php?target=license','license',1940,'A','','','','configuration',1),
(145,5,'lbl_reviews_management','index.php?target=estore_reviews_management','estore_reviews_management',2040,'A','','','estore_products_review','',1),
(143,3,'lbl_ps_offers','index.php?target=promosuite','promosuite',1820,'A','33','','promotion_suite','',1),
(147,7,'lbl_mail_queue','index.php?target=mail_queue','mail_queue',1140,'A','','','','',1),
(153,0,'lbl_tools','','',70,'V','','','seller','users',1),
(154,153,'lbl_messages','index.php?target=message_box','message_box',820,'V','','','messaging_system','',1),
(155,4,'lbl_sellers','index.php?target=user_V','user_V',1360,'A','','','seller','users',1),
(157,3,'lbl_discount_bundles','index.php?target=discount_bundles','discount_bundles',2060,'A','','','promotion_suite','',1),
(158,4,'lbl_suppliers','index.php?target=user_S','user_S',1340,'A','','','','users',1),
(159,7,'lbl_logging','index.php?target=logging','logging',1640,'A','','','','',1),
(160,8,'lbl_orders_statuses','index.php?target=orders_statuses','orders_statuses',1980,'A','','','','',1),
(161,7,'lbl_recurring_list_update','index.php?target=recurring_vr_list_update','recurring_vr_list_update',1780,'A','','','vertical_response','',1),
(163,8,'lbl_maintenance','index.php?target=maintenance','maintenance',2020,'A','','','','',1),
(169,7,'lbl_import_xcart','index.php?target=import&mode=xcart','import',1585,'A','1300','','','import_export',1),
(198,13,'lbl_doc_create_I','index.php?target=docs_I&action=add','docs_I',840,'A','__20','','','orders',1),
(200,13,'lbl_docs_info_I','index.php?target=docs_I','docs_I',400,'A','20','','','orders',1),
(201,12,'lbl_giftcerts','index.php?target=giftcerts','giftcerts',1160,'A','0802','','','',1),
(209,6,'lbl_shipping','index.php?target=shipping','shipping',680,'A','2504','','','shipping-system',1),
(218,149,'lbl_avail_type_incoming','index.php?target=message_box','message_box',460,'A','','','messaging_system','',1),
(219,149,'lbl_sent','index.php?target=message_box&mode=sent','message_box',700,'A','','','messaging_system','',1),
(220,149,'lbl_archive','index.php?target=message_box&mode=archive','message_box',860,'A','','','messaging_system','',1),
(227,45,'lbl_profile_options_admin','index.php?target=user_profiles&user_type=A','user_profiles',980,'A','2502','','','profile_options',1),
(228,45,'lbl_profile_options_supplier','index.php?target=user_profiles&user_type=S','user_profiles',1020,'A','2502','','','profile_options',1),
(229,45,'lbl_additional_sections','index.php?target=user_profiles&mode=fields','user_profiles',1180,'A','','','','profile_options',1),
(230,45,'lbl_sellers','index.php?target=user_profiles&user_type=V','user_profiles',1100,'A','2502','','','profile_options',1),
(231,45,'lbl_profile_options_customer','index.php?target=user_profiles','user_profiles',500,'A','2502','','','profile_options',1),
(236,145,'lbl_reviews_management','index.php?target=estore_reviews_management','estore_reviews_management',260,'A','','','estore_products_review','',1),
(238,154,'lbl_avail_type_incoming','index.php?target=message_box','message_box',520,'V','','','messaging_system','',1),
(239,154,'lbl_sent','index.php?target=message_box&mode=sent','message_box',740,'V','','','messaging_system','',1),
(240,154,'lbl_archive','index.php?target=message_box&mode=archive','message_box',900,'V','','','messaging_system','',1),
(241,154,'lbl_avail_type_incoming','index.php?target=message_box','message_box',540,'V','','','messaging_system','',1),
(242,154,'lbl_sent','index.php?target=message_box&mode=sent','message_box',760,'V','','','messaging_system','',1),
(243,154,'lbl_archive','index.php?target=message_box&mode=archive','message_box',920,'V','','','messaging_system','',1),
(248,2,'lbl_profit_reports','index.php?target=profit_reports','profit_reports',1080,'A','1200','','','orders',1),
(249,0,'lbl_user_create_B','index.php?target=user_B&mode=add','user_B',100,'A','1100','','salesman','sales_manager',1),
(252,0,'lbl_users_B','index.php?target=user_B','user_B',30,'A','1100','','salesman','sales_manager',1),
(253,0,'lbl_affiliate_plans','index.php?target=salesman_plans','salesman_plans',180,'A','1101','','salesman','sales_manager',1),
(254,0,'lbl_commissions','index.php?target=salesman_commissions','salesman_commissions',200,'A','1102','','salesman','sales_manager',1),
(255,0,'lbl_salesman_accounts','index.php?target=salesman_report','salesman_report',210,'A','1104','','salesman','sales_manager',1),
(256,0,'lbl_payment_upload','index.php?target=payment_upload','payment_upload',220,'A','1105','','salesman','',1),
(257,0,'lbl_banners','index.php?target=salesman_banners','salesman_banners',230,'A','1106','','salesman','sales_manager',1),
(258,0,'lbl_multi_tier_affiliates','index.php?target=salesman_level_commissions','salesman_level_commissions',240,'A','1107','','salesman','sales_manager',1),
(259,0,'lbl_affiliate_statistics','index.php?target=banner_info','banner_info',250,'A','1108','','salesman','',1),
(260,0,'lbl_advertising_campaigns','index.php?target=salesman_adv_campaigns','salesman_adv_campaigns',260,'A','1109','','salesman','sales_manager',1),
(261,0,'lbl_discounts','index.php?target=discounts','discounts',270,'A','1111','','salesman','',1),
(262,0,'lbl_targets_premiums','index.php?target=targets','targets',280,'A','1112','','salesman','',1),
(263,3,'lbl_top_menu','index.php?target=top_menu','top_menu',2180,'A','','','','products',1),
(264,3,'lbl_filetypes','index.php?target=filetypes','filetypes',2120,'A','','','','',1),
(265,3,'lbl_manufacturers','index.php?target=manufacturers','manufacturers',1660,'A','1201','','','products',1),
(266,3,'lbl_warranties','index.php?target=warranties','warranties',2160,'A','1202','','','products',1),
(267,3,'lbl_pt_global','index.php?target=product_tabs','product_tabs',1840,'A','','','','products',1),
(268,3,'lbl_special_sections','index.php?target=special_sections','special_sections',2140,'A','1205','','','products',1),
(269,3,'lbl_features','index.php?target=attributes&mode=att','attributes',2080,'A','31','','','',1),
(270,3,'lbl_feature_classes','index.php?target=attributes','attributes',2100,'A','31','','','',1),
(273,5,'lbl_css_styles','index.php?target=custom_css','custom_css',560,'A','2905','','','webmaster',1),
(274,5,'lbl_special_images','index.php?target=special_images','special_images',780,'A','2905','','','webmaster',1),
(276,6,'lbl_carriers','index.php?target=shipping_carriers','shipping_carriers',580,'A','2504','','','shipping-system',1),
(277,6,'lbl_cod_types','index.php?target=cod_types','cod_types',1040,'A','2504','','','shipping-system',1),
(278,6,'lbl_shipping_rates','index.php?target=shipping_rates','shipping_rates',1000,'A','2504','','','shipping-system',1),
(279,6,'lbl_shipping_zones','index.php?target=shipping_zones','shipping_zones',940,'A','2504','','','shipping-system',1),
(280,6,'lbl_taxing_zones','index.php?target=zones','zones',280,'A','2505','','','taxes',1),
(281,5,'lbl_clean_urls_list','index.php?target=clean_urls_list','clean_urls_list',600,'A','2801','','','seo',1),
(282,5,'lbl_custom_facet_urls','index.php?target=custom_facet_urls','custom_facet_urls',800,'A','2800','','','seo',1),
(286,0,'lbl_users_G','index.php?target=user_G','user_G',40,'A','06','','pos','users',1),
(288,0,'lbl_doc_create_G','index.php?target=docs_G&action=add','docs_G',110,'A','__0700','','pos','orders',1),
(289,0,'lbl_docs_info_G','index.php?target=docs_G','docs_G',50,'A','0700','','pos','orders',1),
(290,0,'bl_pos_docs_report_pdf','index.php?target=docs_cash_report&mode=pdf','docs_cash_report',150,'A','0701','','pos','',1),
(291,0,'lbl_pos_orders_report','index.php?target=docs_cash_report','docs_cash_report',130,'A','0701','','pos','',1),
(295,7,'lbl_google_export','index.php?target=google_base','google_base',1604,'A','1300','','','',1),
(296,7,'lbl_ebay_export','index.php?target=ebay_export','ebay_export',1605,'A','1300','','','',1),
(297,7,'lbl_amazon_export','index.php?target=amazon_export','amazon_export',1606,'A','1300','','','',1),
(298,145,'lbl_stop_list','index.php?target=estore_stop_list','estore_stop_list',640,'A','','','estore_products_review','',1),
(299,2,'lbl_profits_cost_history','index.php?target=report_cost_history','report_cost_history',1060,'A','1200','','','orders',1);
UNLOCK TABLES;

-- Add custom menu items into "Other" menu
INSERT INTO `cw_menu` VALUES (null,0,'lbl_other','','',1000,'A','','','','',1);
SET @p=LAST_INSERT_ID();

INSERT INTO `cw_menu` select null,@p, t.title, t.link, tg.target, 1000+tg.orderby, 'A' as area,t.access_level, '' as func_visible, tg.addon, '' as skins_subdir, 1 as is_loggedin from cw_navigation_tabs t inner join cw_navigation_targets tg on t.tab_id=tg.tab_id where (tg.addon like 'custom_%' or tg.addon='flexible_import') and t.link!='';

INSERT INTO `cw_menu` select null,@p, nm.title, nm.link, replace(nm.link,'index.php?target=','') as target, 1000+nm.orderby as orderby, nm.area,nm.access_level, '' as func_visible, nm.addon, '' as skins_subdir, 1 as is_loggedin from cw_navigation_menu nm left join cw_menu m on nm.link=m.link where m.link is null and (nm.addon like 'custom_%' or nm.addon='flexible_import');

-- Delete other menu if there is no subitems
SELECT @cond:=count(*) FROM cw_menu WHERE parent_menu_id=@p;
DELETE FROM cw_menu WHERE (menu_id=@p OR parent_menu_id=@p) AND @cond=0;
