CREATE TABLE IF NOT EXISTS `xfer_products_SWE` (
  `catalogid` int(11) NOT NULL DEFAULT '0',
  `cstock` int(11) DEFAULT '0',
  `InventoryStatusTypeID` varchar(255) DEFAULT NULL,
  `pother1` varchar(50) DEFAULT NULL,
  `DisplayInventoryQuantiy` varchar(255) DEFAULT NULL,
  `cname` varchar(255) DEFAULT NULL,
  `cdescription` text,
  `cimageurl` varchar(100) DEFAULT NULL,
  `ccode` varchar(50) DEFAULT NULL,
  `mfg` varchar(255) DEFAULT NULL,
  `cvintage` varchar(50) DEFAULT NULL,
  `vname` varchar(50) DEFAULT NULL,
  `name` varchar(225) DEFAULT NULL,
  `ProprietaryName` varchar(50) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `cregion` varchar(50) DEFAULT NULL,
  `Appellation` varchar(50) DEFAULT NULL,
  `Subappellation` varchar(50) DEFAULT NULL,
  `csize` varchar(50) DEFAULT NULL,
  `SugarContent` varchar(50) DEFAULT 'Sugar Content',
  `WineClubFeaturedDate` varchar(50) DEFAULT NULL,
  `WineClubFeaturedType` varchar(50) DEFAULT NULL,
  `RobertParkerRating` varchar(50) DEFAULT NULL,
  `RobertParkerReview` text,
  `WineSpectatorRating` varchar(50) DEFAULT NULL,
  `WineSpectatorReview` text,
  `WineEnthusiaisRating` varchar(50) DEFAULT NULL,
  `WineEnthusiastReview` text,
  `StephenTanzerRating` varchar(50) DEFAULT NULL,
  `StepehnTanzerReview` text,
  `DecanterRating` varchar(50) DEFAULT NULL,
  `DecanterReview` text,
  `BeverageTastingInstituteRating` varchar(50) DEFAULT NULL,
  `BeverageTastingInstituteReview` text,
  `MichaelJacksonRating` varchar(50) DEFAULT NULL,
  `MichaelJacksonReview` varchar(50) DEFAULT NULL,
  `WineSpiritsRating` varchar(50) DEFAULT NULL,
  `WineSpiritsReview` text,
  `WineryReview` text,
  `tname` varchar(100) DEFAULT NULL,
  `TaxPercentage` varchar(255) DEFAULT NULL,
  `cprice` decimal(19,4) DEFAULT '0.0000',
  `ctwelvebottleprice` decimal(19,4) NOT NULL DEFAULT '0.0000',
  `Cost` decimal(19,4) DEFAULT '0.0000',
  `ctwelvebottlecost` decimal(19,4) DEFAULT '0.0000',
  `ccategory` int(11) DEFAULT '0',
  `cdescurl` varchar(100) DEFAULT NULL,
  `features` varchar(100) DEFAULT NULL,
  `weight` varchar(20) DEFAULT NULL,
  `subcategoryid` int(11) DEFAULT '0',
  `retailprice` decimal(19,4) DEFAULT '0.0000',
  `specialoffer` varchar(100) DEFAULT NULL,
  `buttonimage` varchar(100) DEFAULT NULL,
  `pother6` varchar(50) DEFAULT NULL,
  `pother2` varchar(100) DEFAULT NULL,
  `pother3` varchar(50) DEFAULT NULL,
  `cdateavailable` datetime DEFAULT NULL,
  `allowusertext` varchar(100) DEFAULT NULL,
  `pother4` varchar(255) DEFAULT NULL,
  `pother5` varchar(50) DEFAULT NULL,
  `userid` varchar(50) DEFAULT NULL,
  `keywords` varchar(255) DEFAULT NULL,
  `meta_description` text,
  `template` varchar(100) DEFAULT NULL,
  `extendedimage` varchar(100) DEFAULT NULL,
  `extendeddesc` text,
  `selectlist` varchar(255) DEFAULT NULL,
  `level3` varchar(255) DEFAULT NULL,
  `level4` varchar(255) DEFAULT NULL,
  `level5` varchar(255) DEFAULT NULL,
  `minimumquantity` int(11) DEFAULT '0',
  `supplierid` int(11) DEFAULT '0',
  `crossselling` varchar(255) DEFAULT NULL,
  `hide` tinyint(1) DEFAULT '0',
  `productmatch` varchar(100) DEFAULT NULL,
  `customermatch` varchar(100) DEFAULT NULL,
  `orderattachment` varchar(200) DEFAULT NULL,
  `orderdownload` varchar(200) DEFAULT NULL,
  `groupfordiscount` varchar(50) DEFAULT NULL,
  `clanguage` varchar(50) DEFAULT NULL,
  `points` int(11) DEFAULT '0',
  `pointstobuy` int(11) DEFAULT '0',
  `price2` decimal(19,4) DEFAULT '0.0000',
  `price3` decimal(19,4) DEFAULT '0.0000',
  `billprice` decimal(19,4) DEFAULT '0.0000',
  `billinstallments` int(11) DEFAULT NULL,
  `billinstallmenttype` varchar(50) DEFAULT NULL,
  `billinterval` int(11) DEFAULT NULL,
  `maximumquantity` int(11) DEFAULT '0',
  `frontpage` varchar(100) DEFAULT NULL,
  `inventoryproducts` varchar(255) DEFAULT NULL,
  `taxfree` tinyint(1) DEFAULT '0',
  `freeshipping` tinyint(1) DEFAULT '0',
  `stocktype` varchar(50) DEFAULT NULL,
  `isfeatured` varchar(50) DEFAULT NULL,
  `isbestseller` varchar(50) DEFAULT NULL,
  `isspecial` varchar(50) DEFAULT NULL,
  `iscollectable` varchar(50) DEFAULT NULL,
  `itemnotdiscountable` varchar(50) DEFAULT NULL,
  `avail_code` int(11) DEFAULT '0',
  `sku` varchar(50) DEFAULT NULL,
  UNIQUE KEY `catalogid_2` (`catalogid`),
  KEY `catalogid` (`catalogid`),
  KEY `cstock` (`cstock`),
  KEY `avail_code` (`avail_code`),
  KEY `ccode` (`ccode`),
  KEY `mfg` (`mfg`),
  KEY `cvintage` (`cvintage`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
