CREATE TABLE IF NOT EXISTS `pos_xref` (
  `Item Number` int(11) NOT NULL AUTO_INCREMENT,
  `Item Name` varchar(255) NOT NULL,
  `Item Description` text NOT NULL,
  `Alternate Lookup` varchar(255) NOT NULL,
  `Attribute` varchar(20) NOT NULL,
  `Size` varchar(20) NOT NULL,
  `Average Unit Cost` decimal(19,4) NOT NULL,
  `Regular Price` decimal(19,4) NOT NULL,
  `MSRP` decimal(19,4) NOT NULL,
  `Custom Price 1` decimal(19,4) NOT NULL,
  `Custom Price 2` decimal(19,4) NOT NULL,
  `Custom Price 3` decimal(19,4) NOT NULL,
  `Custom Price 4` decimal(19,4) NOT NULL,
  `UPC` varchar(255) NOT NULL,
  `Department Name` varchar(75) NOT NULL,
  `Department Code` varchar(20) NOT NULL,
  `Vendor Code` int(11) NOT NULL,
  `Vendor Name` varchar(255) NOT NULL,
  `Qty 1` int(11) NOT NULL,
  `On Order Qty` int(11) NOT NULL DEFAULT '0',
  `Reorder Point 1` int(11) NOT NULL DEFAULT '0',
  `Custom Field 1` varchar(255) NOT NULL,
  `Custom Field 2` varchar(255) NOT NULL,
  `Custom Field 3` int(11) NOT NULL,
  `Custom Field 4` varchar(10) NOT NULL,
  `Custom Field 5` varchar(255) NOT NULL,
  PRIMARY KEY (`Item Number`),
  KEY `Custom Field 5` (`Custom Field 5`),
  KEY `Alternate Lookup` (`Alternate Lookup`),
  KEY `Average Unit Cost` (`Average Unit Cost`),
  KEY `MSRP` (`MSRP`)
) ENGINE=MyISAM AUTO_INCREMENT=149845 DEFAULT CHARSET=latin1;
