CREATE TABLE IF NOT EXISTS `feeds_item_compare` (
  `table_id` int(11) NOT NULL AUTO_INCREMENT,
  `Source` varchar(50) DEFAULT NULL,
  `Wine` varchar(255) DEFAULT NULL,
  `wholesaler` varchar(50) DEFAULT NULL,
  `Producer` varchar(255) DEFAULT NULL,
  `Name` varchar(255) DEFAULT NULL,
  `Vintage` varchar(50) DEFAULT NULL,
  `size` varchar(50) DEFAULT NULL,
  `block` smallint(6) DEFAULT NULL,
  `add_to_hub` smallint(6) DEFAULT NULL,
  `xref` varchar(50) DEFAULT NULL,
  `catalogid` int(11) DEFAULT NULL,
  `dup_catid` int(11) DEFAULT NULL,
  `bottles_per_case` int(11) DEFAULT NULL,
  `cost` double DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `Region` varchar(50) DEFAULT NULL,
  `varietal` varchar(50) DEFAULT NULL,
  `Appellation` varchar(50) DEFAULT NULL,
  `sub-appellation` varchar(50) DEFAULT NULL,
  `Parker_rating` varchar(50) DEFAULT NULL,
  `Parker_review` mediumtext,
  `Spectator_rating` varchar(50) DEFAULT NULL,
  `Spectator_review` mediumtext,
  `Tanzer_rating` varchar(50) DEFAULT NULL,
  `Tanzer_review` mediumtext,
  `W&S_rating` varchar(50) DEFAULT NULL,
  `W&S_review` mediumtext,
  `Description` mediumtext,
  `store_id` int(11) DEFAULT NULL,
  `qty_in_stock` int(11) DEFAULT NULL,
  `supplier_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`table_id`),
  KEY `supplier_id` (`supplier_id`)
) ENGINE=MyISAM AUTO_INCREMENT=312499995 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `item` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `dup_catid` int(11) DEFAULT '0',
  `Producer` varchar(50) DEFAULT NULL,
  `name` varchar(225) DEFAULT NULL,
  `Vintage` varchar(50) DEFAULT NULL,
  `Size` varchar(50) DEFAULT NULL,
  `cimageurl` varchar(50) DEFAULT NULL,
  `extendedimage` varchar(50) DEFAULT NULL,
  `TareWeight` double DEFAULT '4',
  `LongDesc` text,
  `Region` varchar(50) DEFAULT NULL,
  `drysweet` varchar(50) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `keywords` varchar(225) DEFAULT NULL,
  `varietal` varchar(50) DEFAULT NULL,
  `Appellation` varchar(50) DEFAULT NULL,
  `sub-appellation` varchar(50) DEFAULT NULL,
  `RP Rating` varchar(50) DEFAULT NULL,
  `RP Review` text,
  `WS Rating` varchar(50) DEFAULT NULL,
  `WS Review` text,
  `WE Rating` varchar(50) DEFAULT NULL,
  `WE Review` text,
  `DC Rating` varchar(50) DEFAULT NULL,
  `DC Review` text,
  `ST Rating` varchar(50) DEFAULT NULL,
  `ST Review` text,
  `W&S Rating` varchar(50) DEFAULT NULL,
  `W&S Review` text,
  `BTI Rating` varchar(50) DEFAULT NULL,
  `BTI Review` text,
  `Winery Rating` varchar(50) DEFAULT NULL,
  `Winery Review` text,
  `bot_per_case` int(11) DEFAULT '12',
  `initial_xref` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `Producer` (`Producer`),
  KEY `name` (`name`),
  KEY `dup_catid` (`dup_catid`),
  KEY `initial_xref` (`initial_xref`),
  KEY `i_name` (`name`),
  KEY `i_producer` (`Producer`),
  KEY `i_vintage` (`Vintage`),
  KEY `i_region` (`Region`),
  KEY `i_country` (`country`)
) ENGINE=MyISAM AUTO_INCREMENT=787921 DEFAULT CHARSET=latin1;

alter table feeds_item_compare add column dhmd_id int(11) not null default 0;
alter table item add column dhmd_id int(11) not null default 0;
